name: workflow-artifacts
on: 
  push
env:
  ARTIFACT_NAME: myartifact 

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        #run: 
      - name: Upload the artifact
        run:  actions/upload-artifact@v2.2.4
        with:
          - name: ${{ env.ARTIFACT_NAME }}
            path: .
        
      
